# Generated by Django 4.0.3 on 2022-03-05 06:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Product')),
                ('category', models.CharField(choices=[('other', 'Other'), ('good', 'Goods'), ('service', 'Services'), ('pharma', 'Medicines'), ('food', 'Food')], default='other', max_length=30, verbose_name='Category')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Description')),
                ('product_pic', models.ImageField(blank=True, null=True, upload_to='product_pics', verbose_name='Picture')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField(verbose_name='Review')),
                ('rating', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('moderation_status', models.BooleanField(default=False, verbose_name='Moderation Status')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('update_date', models.DateTimeField(auto_now_add=True, verbose_name='Updated at')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='webapp.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
            },
        ),
    ]
